/// <reference path="../.pb/pb_data/types.d.ts" />

// DO NOT EDIT THIS FILE DIRECTLY //

const PB_SUPERUSERS = [{ email: "super", password: "user" }];
const PB_USERS = [{ email: "normal", password: "user" }];

migrate(
  (app) => {
    let superusers = app.findCollectionByNameOrId("_superusers");

    for (const item of PB_SUPERUSERS) {
      let record = new Record(superusers);
      record.set("email", item.email);
      record.set("password", item.password);
      app.save(record);
    }

    let users = app.findCollectionByNameOrId("users");
    for (const item of PB_USERS) {
      let record = new Record(users);
      record.set("email", item.email);
      record.set("password", item.password);
      record.set("verified", true);
      if (item.name !== undefined) record.set("name", item.name);
      app.save(record);
    }
  },
  (app) => {
    for (const item of PB_SUPERUSERS) {
      try {
        let record = app.findAuthRecordByEmail("_superusers", item.email);
        app.delete(record);
      } catch (_) {}
    }

    for (const item of PB_USERS) {
      try {
        let record = app.findAuthRecordByEmail("users", item.email);
        app.delete(record);
      } catch (_) {}
    }
  }
);
